// heistWords.js — Word pool for Word Heist
// Each entry: { word: string (7-15 uppercase letters), hint: string[] (1-3 categories) }

export const wordPool = [
  // Occupations
  { word: "DETECTIVE",      hint: ["Occupation", "Crime"] },
  { word: "SAFECRACKER",    hint: ["Occupation", "Crime"] },
  { word: "POLITICIAN",     hint: ["Occupation", "Government"] },
  { word: "ARCHITECT",      hint: ["Occupation"] },
  { word: "CARPENTER",      hint: ["Occupation"] },
  { word: "PLUMBER",        hint: ["Occupation"] },
  { word: "SURGEON",        hint: ["Occupation", "Science"] },
  { word: "ATTORNEY",       hint: ["Occupation", "Crime"] },
  { word: "ENGINEER",       hint: ["Occupation", "Technology"] },
  { word: "PROFESSOR",      hint: ["Occupation", "Education"] },
  { word: "PHARMACIST",     hint: ["Occupation", "Science"] },
  { word: "BARTENDER",      hint: ["Occupation"] },
  { word: "LOCKSMITH",      hint: ["Occupation", "Crime"] },
  { word: "NAVIGATOR",      hint: ["Occupation"] },
  { word: "CONDUCTOR",      hint: ["Occupation", "Music"] },
  { word: "JOURNALIST",     hint: ["Occupation"] },
  { word: "THERAPIST",      hint: ["Occupation", "Science"] },
  { word: "BODYGUARD",      hint: ["Occupation", "Crime"] },
  { word: "INFORMANT",      hint: ["Occupation", "Crime"] },
  { word: "MERCENARY",      hint: ["Occupation", "Crime"] },

  // Persons
  { word: "PEDESTRIAN",     hint: ["Person"] },
  { word: "CELEBRITY",      hint: ["Person"] },
  { word: "FUGITIVE",       hint: ["Person", "Crime"] },
  { word: "CRIMINAL",       hint: ["Person", "Crime"] },
  { word: "ACCOMPLICE",     hint: ["Person", "Crime"] },
  { word: "VIGILANTE",      hint: ["Person", "Crime"] },
  { word: "MASTERMIND",     hint: ["Person", "Crime"] },
  { word: "IMPOSTER",       hint: ["Person", "Crime"] },
  { word: "SPECTATOR",      hint: ["Person"] },
  { word: "VOLUNTEER",      hint: ["Person"] },
  { word: "IMMIGRANT",      hint: ["Person"] },
  { word: "ADVERSARY",      hint: ["Person", "Crime"] },
  { word: "INFORMER",       hint: ["Person", "Crime"] },
  { word: "DIPLOMAT",       hint: ["Person", "Government"] },
  { word: "GUARDIAN",       hint: ["Person"] },
  { word: "PRISONER",       hint: ["Person", "Crime"] },
  { word: "RECRUITER",      hint: ["Person", "Occupation"] },

  // Crime & Law
  { word: "BURGLARY",       hint: ["Crime"] },
  { word: "BLACKMAIL",      hint: ["Crime"] },
  { word: "EXTORTION",      hint: ["Crime"] },
  { word: "SMUGGLING",      hint: ["Crime"] },
  { word: "FORGERY",        hint: ["Crime"] },
  { word: "HIJACKING",      hint: ["Crime"] },
  { word: "AMBUSCADE",      hint: ["Crime", "Military"] },
  { word: "CONSPIRACY",     hint: ["Crime", "Government"] },
  { word: "ESPIONAGE",      hint: ["Crime", "Spy"] },
  { word: "SABOTAGE",       hint: ["Crime", "Military"] },
  { word: "KIDNAPPING",     hint: ["Crime"] },
  { word: "STALKING",       hint: ["Crime"] },
  { word: "INCENDIARY",     hint: ["Crime"] },
  { word: "CONTRABAND",     hint: ["Crime"] },
  { word: "LAUNDERING",     hint: ["Crime", "Finance"] },
  { word: "EMBEZZLE",       hint: ["Crime", "Finance"] },
  { word: "LARCENY",        hint: ["Crime"] },
  { word: "HOSTAGE",        hint: ["Crime"] },
  { word: "GETAWAY",        hint: ["Crime"] },

  // Casino & Games
  { word: "ROULETTE",       hint: ["Casino", "Games"] },
  { word: "BLACKJACK",      hint: ["Casino", "Games"] },
  { word: "JACKPOT",        hint: ["Casino", "Games"] },
  { word: "GAMBLING",       hint: ["Casino"] },
  { word: "BLUFFING",       hint: ["Casino", "Games"] },
  { word: "WAGERING",       hint: ["Casino"] },
  { word: "CROUPIER",       hint: ["Casino", "Occupation"] },
  { word: "CARDSHARP",      hint: ["Casino", "Occupation"] },
  { word: "BACCARAT",       hint: ["Casino", "Games"] },
  { word: "TOURNAMENT",     hint: ["Games", "Sports"] },
  { word: "CHECKERS",       hint: ["Games"] },
  { word: "DOMINOES",       hint: ["Games"] },
  { word: "STRATEGY",       hint: ["Games"] },

  // Animals
  { word: "CROCODILE",      hint: ["Animal", "Reptile"] },
  { word: "ALLIGATOR",      hint: ["Animal", "Reptile"] },
  { word: "ELEPHANT",       hint: ["Animal", "Mammal"] },
  { word: "CHEETAH",        hint: ["Animal", "Mammal"] },
  { word: "PANTHER",        hint: ["Animal", "Mammal"] },
  { word: "LEOPARD",        hint: ["Animal", "Mammal"] },
  { word: "JAGUARUNDI",     hint: ["Animal", "Mammal"] },
  { word: "WOLVERINE",      hint: ["Animal", "Mammal"] },
  { word: "MONGOOSE",       hint: ["Animal", "Mammal"] },
  { word: "SCORPION",       hint: ["Animal", "Insect"] },
  { word: "TARANTULA",      hint: ["Animal", "Spider"] },
  { word: "CHAMELEON",      hint: ["Animal", "Reptile"] },
  { word: "PIRANHA",        hint: ["Animal", "Fish"] },
  { word: "ANACONDA",       hint: ["Animal", "Reptile"] },
  { word: "BARRACUDA",      hint: ["Animal", "Fish"] },
  { word: "FLAMINGO",       hint: ["Animal", "Bird"] },
  { word: "PELICAN",        hint: ["Animal", "Bird"] },

  // Geography
  { word: "PENINSULA",      hint: ["Geography"] },
  { word: "CONTINENT",      hint: ["Geography"] },
  { word: "ARCHIPELAGO",    hint: ["Geography"] },
  { word: "COASTLINE",      hint: ["Geography", "Nature"] },
  { word: "MARSHLAND",      hint: ["Geography", "Nature"] },
  { word: "SAVANNA",        hint: ["Geography", "Nature"] },
  { word: "PLATEAU",        hint: ["Geography", "Nature"] },
  { word: "GLACIER",        hint: ["Geography", "Nature"] },
  { word: "MERIDIAN",       hint: ["Geography"] },
  { word: "LATITUDE",       hint: ["Geography"] },
  { word: "LONGITUDE",      hint: ["Geography"] },

  // Science & Technology
  { word: "MOLECULE",       hint: ["Science"] },
  { word: "ELECTRON",       hint: ["Science", "Physics"] },
  { word: "HYDROGEN",       hint: ["Science", "Chemistry"] },
  { word: "NITROGEN",       hint: ["Science", "Chemistry"] },
  { word: "CATALYST",       hint: ["Science", "Chemistry"] },
  { word: "MAGNETIC",       hint: ["Science", "Physics"] },
  { word: "RADIATION",      hint: ["Science", "Physics"] },
  { word: "SATELLITE",      hint: ["Technology", "Science"] },
  { word: "DATABASE",       hint: ["Technology"] },
  { word: "ALGORITHM",      hint: ["Technology", "Science"] },
  { word: "ENCRYPTION",     hint: ["Technology", "Crime"] },
  { word: "FIREWALL",       hint: ["Technology"] },
  { word: "PROCESSOR",      hint: ["Technology"] },
  { word: "BANDWIDTH",      hint: ["Technology"] },
  { word: "PROTOCOL",       hint: ["Technology"] },
  { word: "COMPILER",       hint: ["Technology"] },

  // Government & Military
  { word: "PARLIAMENT",     hint: ["Government"] },
  { word: "DEMOCRACY",      hint: ["Government"] },
  { word: "REPUBLIC",       hint: ["Government"] },
  { word: "TRIBUNAL",       hint: ["Government", "Crime"] },
  { word: "BATTALION",      hint: ["Military"] },
  { word: "REGIMENT",       hint: ["Military"] },
  { word: "GARRISON",       hint: ["Military"] },
  { word: "COMMANDER",      hint: ["Military", "Occupation"] },
  { word: "SERGEANT",       hint: ["Military", "Occupation"] },
  { word: "CORPORAL",       hint: ["Military", "Occupation"] },
  { word: "SENTINEL",       hint: ["Military", "Occupation"] },
  { word: "GUERRILLA",      hint: ["Military", "Crime"] },

  // Food & Drink
  { word: "ARTICHOKE",      hint: ["Food", "Vegetable"] },
  { word: "CHOCOLATE",      hint: ["Food"] },
  { word: "CINNAMON",       hint: ["Food", "Spice"] },
  { word: "CARDAMOM",       hint: ["Food", "Spice"] },
  { word: "MUSHROOM",       hint: ["Food", "Nature"] },
  { word: "AVOCADO",        hint: ["Food", "Fruit"] },
  { word: "BLUEBERRY",      hint: ["Food", "Fruit"] },
  { word: "MANDARIN",       hint: ["Food", "Fruit"] },
  { word: "ESPRESSO",       hint: ["Food", "Drink"] },
  { word: "BOURBON",        hint: ["Food", "Drink"] },
  { word: "ABSINTHE",       hint: ["Food", "Drink"] },
  { word: "TEQUILA",        hint: ["Food", "Drink"] },

  // Sports & Fitness
  { word: "MARATHON",       hint: ["Sports", "Running"] },
  { word: "TRIATHLON",      hint: ["Sports"] },
  { word: "WRESTLING",      hint: ["Sports", "Combat"] },
  { word: "FENCING",        hint: ["Sports", "Combat"] },
  { word: "ARCHERY",        hint: ["Sports"] },
  { word: "JAVELIN",        hint: ["Sports"] },
  { word: "DECATHLON",      hint: ["Sports"] },
  { word: "DOWNHILL",       hint: ["Sports", "Skiing"] },
  { word: "LACROSSE",       hint: ["Sports"] },
  { word: "BADMINTON",      hint: ["Sports"] },
  { word: "HANDBALL",       hint: ["Sports"] },
  { word: "VOLLEYBALL",     hint: ["Sports"] },
  { word: "QUARTERBACK",    hint: ["Sports", "Football"] },
  { word: "DEFENDER",       hint: ["Sports", "Military"] },

  // Nature & Weather
  { word: "HURRICANE",      hint: ["Nature", "Weather"] },
  { word: "AVALANCHE",      hint: ["Nature", "Weather"] },
  { word: "BLIZZARD",       hint: ["Nature", "Weather"] },
  { word: "THUNDERSTORM",   hint: ["Nature", "Weather"] },
  { word: "EARTHQUAKE",     hint: ["Nature", "Disaster"] },
  { word: "TORNADO",        hint: ["Nature", "Weather"] },
  { word: "TSUNAMI",        hint: ["Nature", "Disaster"] },
  { word: "WILDFIRE",       hint: ["Nature", "Disaster"] },
  { word: "PERMAFROST",     hint: ["Nature", "Geography"] },
  { word: "SEDIMENT",       hint: ["Nature", "Science"] },
  { word: "STALACTITE",     hint: ["Nature", "Geography"] },
  { word: "STALAGMITE",     hint: ["Nature", "Geography"] },
  { word: "PHOSPHOR",       hint: ["Nature", "Science"] },

  // Equipment & Tools
  { word: "REVOLVER",       hint: ["Equipment", "Crime"] },
  { word: "HOLSTER",        hint: ["Equipment"] },
  { word: "HANDCUFF",       hint: ["Equipment", "Crime"] },
  { word: "DETONATOR",      hint: ["Equipment", "Crime"] },
  { word: "FLASHLIGHT",     hint: ["Equipment"] },
  { word: "BINOCULARS",     hint: ["Equipment"] },
  { word: "COMPASS",        hint: ["Equipment", "Geography"] },
  { word: "CROWBAR",        hint: ["Equipment", "Crime"] },
  { word: "SCANNER",        hint: ["Equipment", "Technology"] },
  { word: "TRANSMITTER",    hint: ["Equipment", "Technology"] },
  { word: "RECEIVER",       hint: ["Equipment", "Technology"] },
  { word: "TELESCOPE",      hint: ["Equipment", "Science"] },
  { word: "MICROSCOPE",     hint: ["Equipment", "Science"] },

  // Misc / Concepts
  { word: "EXCULPATE",      hint: ["Crime", "Legal"] },
  { word: "MOTIVATION",     hint: ["Crime"] },
  { word: "EVIDENCE",       hint: ["Crime", "Legal"] },
  { word: "VERDICT",        hint: ["Crime", "Legal"] },
  { word: "SENTENCE",       hint: ["Crime", "Legal"] },
  { word: "WITNESS",        hint: ["Crime", "Legal"] },
  { word: "WARRANT",        hint: ["Crime", "Legal"] },
  { word: "SUBPOENA",       hint: ["Crime", "Legal"] },
  { word: "PAROLEE",        hint: ["Crime", "Legal"] },
  { word: "PROBATION",      hint: ["Crime", "Legal"] },
  { word: "ACQUITTAL",      hint: ["Crime", "Legal"] },
  { word: "INDICTMENT",     hint: ["Crime", "Legal"] },
  { word: "TESTIMONY",      hint: ["Crime", "Legal"] },
  { word: "UNDERCOVER",     hint: ["Crime", "Spy"] },
  { word: "DISGUISE",       hint: ["Crime", "Spy"] },
  { word: "INFILTRATE",     hint: ["Crime", "Spy"] },
  { word: "RENDEZVOUS",     hint: ["Spy"] },
  { word: "SURVEILLANCE",   hint: ["Crime", "Spy"] },
  { word: "CLANDESTINE",    hint: ["Crime", "Spy"] },
];
