import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = dirname(__filename);

// ─── Config ───────────────────────────────────────────────────────────────────
const WORD_LIST_PATH = join(__dirname, '../wordList.js');
const OUTPUT_PATH    = join(__dirname, '../bootstrapWords.js');

const LONG_MIN = 9;
const LONG_MAX = 14;

const TECHY_RE = /(ENCEPHAL|NEURO|EAE|DAE|SULF|PHEN|CHEM|BLASTU|PHYL|CYTE|PHAGE|INASE|AMIDE|IMIDE)/i;

// ─── Read wordList.js and extract the array ───────────────────────────────────
const raw = readFileSync(WORD_LIST_PATH, 'utf8');

// Pull every quoted string out of the file
const matches = raw.match(/"([^"]+)"/g) || [];
const allWords = matches.map(m => m.replace(/"/g, ''));

console.log(`📖 Total words loaded: ${allWords.length}`);

// ─── Filter ───────────────────────────────────────────────────────────────────
const filtered = allWords
  .map(w => w.toUpperCase())
  .filter(w => {
    if (w.length < LONG_MIN || w.length > LONG_MAX) return false;  // wrong length
    if (!/^[A-Z]+$/.test(w))                         return false;  // non-letters
    if (TECHY_RE.test(w))                             return false;  // jargon
    return true;
  });

console.log(`✅ Words passing filter (${LONG_MIN}–${LONG_MAX} letters, no jargon): ${filtered.length}`);

// ─── Write output ─────────────────────────────────────────────────────────────
const lines = filtered.map(w => `  "${w}",`).join('\n');
const output = `// Auto-generated by scripts/extractBootstrapWords.mjs
// ${filtered.length} curated bootstrap anchor words (${LONG_MIN}–${LONG_MAX} letters)
// Re-run the script any time wordList.js changes.

export default [\n${lines}\n];\n`;

writeFileSync(OUTPUT_PATH, output, 'utf8');

console.log(`📝 Written to: ${OUTPUT_PATH}`);
console.log(`\n── Sample (first 20 words) ──`);
filtered.slice(0, 20).forEach((w, i) => console.log(`  ${i + 1}. ${w}`));